name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - python=3.8
  - pip:
      - wandb==0.10.21
      - pandas==1.1.4
      - pytest==6.2.2
      - scipy==1.5.2
      - protobuf==3.20.0
      - numpy==1.20